KREST-2408: Try longer consumer poll in getConsumerLag integration test (#904)
Increasing the consumer poll time to hopefully address test failure due to `Consumer group offsets could not be found`. 
Test failure: 
https://jenkins.confluent.io/job/confluentinc/job/kafka-rest/job/master/5718/testReport/io.confluent.kafkarest.integration.v3/ConsumerLagsResourceIntegrationTest/getConsumerLag_returnsConsumerLag/
```
[2021-09-13 12:18:29,812] INFO 127.0.0.1 - - [13/Sep/2021:12:18:29 +0000] "GET /v3/clusters/lz7kmpQcRlmmyZFgDkR4JA/consumer-groups/consumer-group-1/lags/topic-1/partitions/0 HTTP/1.1" 404 73 "-" "Jersey/2.34 (HttpUrlConnection 1.8.0_292)" 94 (io.confluent.rest-utils.requests:62)
[2021-09-13 12:18:36,418] ERROR Request Failed with exception  (io.confluent.rest.exceptions.DebuggableExceptionMapper:103)
javax.ws.rs.NotFoundException: Consumer group offsets could not be found.
```
Related testbreak ticket: https://confluentinc.atlassian.net/browse/KREST-2408
Previous testbreak ticket: https://confluentinc.atlassian.net/browse/KREST-2303